name: remake_tsiro
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  video_player: ^2.7.2
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  smooth_star_rating_null_safety: ^1.0.4+2
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/video/bg.mp4
    - assets/image/recette.jpg




